/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class LynxEngine_Android_JNI */

#ifndef _Included_LynxEngine_Android_JNI
#define _Included_LynxEngine_Android_JNI
#ifdef __cplusplus
extern "C" {
#endif
#undef LynxEngine_Android_JNI_enableLog
#define LynxEngine_Android_JNI_enableLog 1L
/*
 * Class:     LynxEngine_Android_JNI
 * Method:    OnLoad
 * Signature: (LLynxEngine/Android/NativeActivity;)V
 */
JNIEXPORT void JNICALL Java_LynxEngine_Android_JNI_OnLoad
  (JNIEnv *, jclass, jobject);

/*
 * Class:     LynxEngine_Android_JNI
 * Method:    IsApplicationInForeground
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_LynxEngine_Android_JNI_IsApplicationInForeground
  (JNIEnv *, jclass);

/*
 * Class:     LynxEngine_Android_JNI
 * Method:    OnBackPressed
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_LynxEngine_Android_JNI_OnBackPressed
  (JNIEnv *, jclass);

/*
 * Class:     LynxEngine_Android_JNI
 * Method:    OnTouchEvent
 * Signature: (ILandroid/view/MotionEvent;)V
 */
JNIEXPORT void JNICALL Java_LynxEngine_Android_JNI_OnTouchEvent
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     LynxEngine_Android_JNI
 * Method:    OnTouch
 * Signature: (ILandroid/view/MotionEvent;)V
 */
JNIEXPORT void JNICALL Java_LynxEngine_Android_JNI_OnTouch
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     LynxEngine_Android_JNI
 * Method:    OnScroll
 * Signature: (ILandroid/view/MotionEvent;Landroid/view/MotionEvent;FF)V
 */
JNIEXPORT void JNICALL Java_LynxEngine_Android_JNI_OnScroll
  (JNIEnv *, jclass, jint, jobject, jobject, jfloat, jfloat);

/*
 * Class:     LynxEngine_Android_JNI
 * Method:    OnAlertDialogClick
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_LynxEngine_Android_JNI_OnAlertDialogClick
  (JNIEnv *, jclass, jint);

/*
 * Class:     LynxEngine_Android_JNI
 * Method:    OnQueryInventoryFinished
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_LynxEngine_Android_JNI_OnQueryInventoryFinished
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     LynxEngine_Android_JNI
 * Method:    OnVerifyDeveloperPayload
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_LynxEngine_Android_JNI_OnVerifyDeveloperPayload
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring);

/*
 * Class:     LynxEngine_Android_JNI
 * Method:    OnVerifyPurchasePromoCode
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_LynxEngine_Android_JNI_OnVerifyPurchasePromoCode
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring);

/*
 * Class:     LynxEngine_Android_JNI
 * Method:    OnConsumeFinished
 * Signature: (ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_LynxEngine_Android_JNI_OnConsumeFinished
  (JNIEnv *, jclass, jint, jstring, jstring, jstring);

/*
 * Class:     LynxEngine_Android_JNI
 * Method:    OnIapPurchaseFinished
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_LynxEngine_Android_JNI_OnIapPurchaseFinished
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     LynxEngine_Android_JNI
 * Method:    OnIapPurchaseFailed
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_LynxEngine_Android_JNI_OnIapPurchaseFailed
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     LynxEngine_Android_JNI
 * Method:    UpdateText
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_LynxEngine_Android_JNI_UpdateText
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     LynxEngine_Android_JNI
 * Method:    SetDownloadTotalSize
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_LynxEngine_Android_JNI_SetDownloadTotalSize
  (JNIEnv *, jclass, jlong);

/*
 * Class:     LynxEngine_Android_JNI
 * Method:    SetDownloadProgressSize
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_LynxEngine_Android_JNI_SetDownloadProgressSize
  (JNIEnv *, jclass, jlong);

/*
 * Class:     LynxEngine_Android_JNI
 * Method:    OnFinishFacebookLogin
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_LynxEngine_Android_JNI_OnFinishFacebookLogin
  (JNIEnv *, jclass, jstring);

/*
 * Class:     LynxEngine_Android_JNI
 * Method:    OnFinishQueryFacebookAccountData
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_LynxEngine_Android_JNI_OnFinishQueryFacebookAccountData
  (JNIEnv *, jclass, jstring);

/*
 * Class:     LynxEngine_Android_JNI
 * Method:    OnFinishQueryFacebookFriendsData
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_LynxEngine_Android_JNI_OnFinishQueryFacebookFriendsData
  (JNIEnv *, jclass, jstring);

/*
 * Class:     LynxEngine_Android_JNI
 * Method:    OnFinishFacebookShareLink
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_LynxEngine_Android_JNI_OnFinishFacebookShareLink
  (JNIEnv *, jclass, jstring);

/*
 * Class:     LynxEngine_Android_JNI
 * Method:    OnFinishFacebookUploadPic
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_LynxEngine_Android_JNI_OnFinishFacebookUploadPic
  (JNIEnv *, jclass, jstring);

/*
 * Class:     LynxEngine_Android_JNI
 * Method:    HandleURL
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_LynxEngine_Android_JNI_HandleURL
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     LynxEngine_Android_JNI
 * Method:    SetAdvertisingIDString
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_LynxEngine_Android_JNI_SetAdvertisingIDString
  (JNIEnv *, jclass, jstring);

/*
 * Class:     LynxEngine_Android_JNI
 * Method:    OnClickRatingDialog
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_LynxEngine_Android_JNI_OnClickRatingDialog
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
